
import { Word, LexileRange } from './types';

export const LEXILE_WORDS: Record<LexileRange, Word[]> = {
  [LexileRange.BR_200L]: [
    { word: 'apple', lexile: 100 }, { word: 'ball', lexile: 50 }, { word: 'cat', lexile: 80 },
    { word: 'dog', lexile: 90 }, { word: 'egg', lexile: 120 }, { word: 'fish', lexile: 150 },
    { word: 'go', lexile: 20 }, { word: 'hat', lexile: 110 }, { word: 'ice', lexile: 180 },
    { word: 'jump', lexile: 140 }, { word: 'kite', lexile: 190 }, { word: 'lamp', lexile: 170 },
    { word: 'milk', lexile: 130 }, { word: 'nest', lexile: 160 }, { word: 'owl', lexile: 195 },
    { word: 'pig', lexile: 70 }, { word: 'queen', lexile: 200 }, { word: 'rain', lexile: 150 },
    { word: 'sun', lexile: 40 }, { word: 'tree', lexile: 120 }, { word: 'up', lexile: 30 },
    { word: 'van', lexile: 140 }, { word: 'water', lexile: 160 }, { word: 'box', lexile: 95 },
    { word: 'yellow', lexile: 185 }, { word: 'zoo', lexile: 60 }, { word: 'bed', lexile: 85 },
    { word: 'cake', lexile: 145 }, { word: 'duck', lexile: 115 }, { word: 'frog', lexile: 155 },
    { word: 'girl', lexile: 105 }, { word: 'hand', lexile: 125 }, { word: 'ink', lexile: 190 },
    { word: 'jam', lexile: 135 }, { word: 'king', lexile: 175 }, { word: 'leaf', lexile: 165 },
    { word: 'moon', lexile: 195 }, { word: 'nose', lexile: 145 }, { word: 'pen', lexile: 75 },
    { word: 'quack', lexile: 190 }, { word: 'rock', lexile: 135 }, { word: 'ship', lexile: 180 },
    { word: 'tent', lexile: 155 }, { word: 'uncle', lexile: 195 }, { word: 'vest', lexile: 170 },
    { word: 'wolf', lexile: 185 }, { word: 'yard', lexile: 145 }, { word: 'zebra', lexile: 165 },
    { word: 'ant', lexile: 110 }, { word: 'bell', lexile: 130 }
  ],
  [LexileRange.L200_400]: [
    { word: 'adventure', lexile: 350 }, { word: 'bicycle', lexile: 320 }, { word: 'careful', lexile: 280 },
    { word: 'distance', lexile: 390 }, { word: 'energy', lexile: 340 }, { word: 'forest', lexile: 260 },
    { word: 'garden', lexile: 220 }, { word: 'holiday', lexile: 310 }, { word: 'island', lexile: 370 },
    { word: 'journey', lexile: 385 }, { word: 'kitchen', lexile: 240 }, { word: 'library', lexile: 330 },
    { word: 'mountain', lexile: 395 }, { word: 'neighbor', lexile: 360 }, { word: 'ocean', lexile: 300 },
    { word: 'palace', lexile: 380 }, { word: 'quietly', lexile: 345 }, { word: 'river', lexile: 215 },
    { word: 'science', lexile: 395 }, { word: 'ticket', lexile: 325 }, { word: 'useful', lexile: 335 },
    { word: 'village', lexile: 365 }, { word: 'weather', lexile: 355 }, { word: 'yesterday', lexile: 390 },
    { word: 'amazing', lexile: 315 }, { word: 'beautiful', lexile: 375 }, { word: 'camera', lexile: 290 },
    { word: 'different', lexile: 380 }, { word: 'exciting', lexile: 340 }, { word: 'family', lexile: 230 },
    { word: 'glasses', lexile: 275 }, { word: 'healthy', lexile: 350 }, { word: 'imagine', lexile: 385 },
    { word: 'jacket', lexile: 285 }, { word: 'kangaroo', lexile: 320 }, { word: 'listen', lexile: 245 },
    { word: 'machine', lexile: 395 }, { word: 'nature', lexile: 330 }, { word: 'orange', lexile: 225 },
    { word: 'picture', lexile: 310 }, { word: 'question', lexile: 360 }, { word: 'remember', lexile: 390 },
    { word: 'special', lexile: 350 }, { word: 'travel', lexile: 340 }, { word: 'universe', lexile: 400 },
    { word: 'visitor', lexile: 370 }, { word: 'window', lexile: 210 }, { word: 'young', lexile: 250 },
    { word: 'animal', lexile: 265 }, { word: 'balloon', lexile: 295 }
  ],
  [LexileRange.L400_600]: [
    { word: 'celebrate', lexile: 520 }, { word: 'dangerous', lexile: 580 }, { word: 'excellent', lexile: 550 },
    { word: 'furniture', lexile: 490 }, { word: 'grateful', lexile: 510 }, { word: 'history', lexile: 460 },
    { word: 'important', lexile: 540 }, { word: 'knowledge', lexile: 590 }, { word: 'language', lexile: 530 },
    { word: 'material', lexile: 470 }, { word: 'necessary', lexile: 600 }, { word: 'opposite', lexile: 560 },
    { word: 'passenger', lexile: 480 }, { word: 'quality', lexile: 570 }, { word: 'responsible', lexile: 595 },
    { word: 'separate', lexile: 515 }, { word: 'together', lexile: 420 }, { word: 'understand', lexile: 450 },
    { word: 'valuable', lexile: 585 }, { word: 'wonderful', lexile: 440 }, { word: 'atmosphere', lexile: 590 },
    { word: 'background', lexile: 485 }, { word: 'character', lexile: 535 }, { word: 'development', lexile: 600 },
    { word: 'education', lexile: 555 }, { word: 'frequency', lexile: 595 }, { word: 'government', lexile: 575 },
    { word: 'happiness', lexile: 410 }, { word: 'immediate', lexile: 580 }, { word: 'judgment', lexile: 590 },
    { word: 'literature', lexile: 595 }, { word: 'mysterious', lexile: 545 }, { word: 'neighborhood', lexile: 465 },
    { word: 'opportunity', lexile: 600 }, { word: 'pollution', lexile: 565 }, { word: 'refrigerator', lexile: 525 },
    { word: 'successful', lexile: 550 }, { word: 'temperature', lexile: 580 }, { word: 'unusual', lexile: 510 },
    { word: 'vegetable', lexile: 430 }, { word: 'witness', lexile: 540 }, { word: 'yesteryear', lexile: 595 },
    { word: 'activity', lexile: 445 }, { word: 'boundary', lexile: 585 }, { word: 'creativity', lexile: 560 },
    { word: 'discussion', lexile: 515 }, { word: 'environment', lexile: 590 }, { word: 'flexible', lexile: 570 },
    { word: 'generation', lexile: 580 }, { word: 'highlight', lexile: 495 }
  ],
  [LexileRange.L600_800]: [
    { word: 'abandonment', lexile: 720 }, { word: 'biological', lexile: 780 }, { word: 'circumstance', lexile: 750 },
    { word: 'discrimination', lexile: 790 }, { word: 'experimental', lexile: 710 }, { word: 'fundamental', lexile: 760 },
    { word: 'hypothetical', lexile: 800 }, { word: 'investigation', lexile: 740 }, { word: 'metaphorical', lexile: 795 },
    { word: 'negotiation', lexile: 730 }, { word: 'organizational', lexile: 770 }, { word: 'parliamentary', lexile: 795 },
    { word: 'quantitative', lexile: 800 }, { word: 'relationship', lexile: 650 }, { word: 'standardization', lexile: 800 },
    { word: 'transformation', lexile: 725 }, { word: 'unpredictable', lexile: 755 }, { word: 'vulnerability', lexile: 785 },
    { word: 'accumulation', lexile: 745 }, { word: 'bibliography', lexile: 790 }, { word: 'comprehension', lexile: 680 },
    { word: 'demonstration', lexile: 715 }, { word: 'enthusiastically', lexile: 765 }, { word: 'fluctuation', lexile: 775 },
    { word: 'generalization', lexile: 790 }, { word: 'humanitarian', lexile: 795 }, { word: 'illustration', lexile: 690 },
    { word: 'justification', lexile: 780 }, { word: 'maintenance', lexile: 705 }, { word: 'notwithstanding', lexile: 800 },
    { word: 'observation', lexile: 660 }, { word: 'phenomenon', lexile: 795 }, { word: 'reconciliation', lexile: 785 },
    { word: 'sophisticated', lexile: 790 }, { word: 'theoretical', lexile: 775 }, { word: 'utilization', lexile: 795 },
    { word: 'visualization', lexile: 760 }, { word: 'wilderness', lexile: 640 }, { word: 'architecture', lexile: 735 },
    { word: 'broadcast', lexile: 620 }, { word: 'consequently', lexile: 710 }, { word: 'description', lexile: 630 },
    { word: 'engagement', lexile: 695 }, { word: 'foundation', lexile: 655 }, { word: 'guarantee', lexile: 740 },
    { word: 'interpretation', lexile: 785 }, { word: 'mechanism', lexile: 760 }, { word: 'philosophy', lexile: 795 },
    { word: 'psychological', lexile: 790 }, { word: 'remarkable', lexile: 685 }
  ],
  [LexileRange.L800_1000]: [
    { word: 'accommodations', lexile: 850 }, { word: 'characteristic', lexile: 820 }, { word: 'deterioration', lexile: 980 },
    { word: 'entrepreneur', lexile: 920 }, { word: 'flamboyant', lexile: 890 }, { word: 'hierarchical', lexile: 940 },
    { word: 'lackadaisical', lexile: 930 }, { word: 'philanthropist', lexile: 910 }, { word: 'rhetorical', lexile: 860 },
    { word: 'trepidation', lexile: 990 }, { word: 'yesteryear', lexile: 830 }, { word: 'zenith', lexile: 940 },
    { word: 'belligerent', lexile: 900 }, { word: 'dichotomy', lexile: 880 }, { word: 'impeccable', lexile: 940 },
    { word: 'nefarious', lexile: 950 }, { word: 'yieldingly', lexile: 810 }, { word: 'zealously', lexile: 840 },
    { word: 'gregarious', lexile: 880 }, { word: 'fastidious', lexile: 970 }, { word: 'bureaucracy', lexile: 995 },
    { word: 'impetuous', lexile: 870 }, { word: 'loquacious', lexile: 960 }, { word: 'meticulous', lexile: 925 },
    { word: 'parsimony', lexile: 985 }, { word: 'sagacious', lexile: 895 }, { word: 'venerable', lexile: 915 },
    { word: 'capricious', lexile: 945 }, { word: 'ephemeral', lexile: 975 }, { word: 'grandeur', lexile: 845 },
    { word: 'harmonious', lexile: 815 }, { word: 'innovative', lexile: 865 }, { word: 'judicious', lexile: 910 },
    { word: 'labyrinth', lexile: 935 }, { word: 'notorious', lexile: 825 }, { word: 'oblivion', lexile: 855 },
    { word: 'paradoxical', lexile: 990 }, { word: 'quintessential', lexile: 1000 }, { word: 'radiance', lexile: 835 },
    { word: 'scrupulous', lexile: 955 }, { word: 'tranquility', lexile: 885 }, { word: 'ubiquity', lexile: 965 },
    { word: 'validity', lexile: 805 }, { word: 'whimsical', lexile: 875 }, { word: 'exquisite', lexile: 905 },
    { word: 'formidable', lexile: 980 }, { word: 'galvanize', lexile: 920 }, { word: 'hypnotic', lexile: 840 },
    { word: 'intuitive', lexile: 915 }, { word: 'juxtapose', lexile: 995 }
  ],
  [LexileRange.L1000_PLUS]: [
    { word: 'grandiloquent', lexile: 1200 }, { word: 'idiosyncrasy', lexile: 1100 }, { word: 'juxtaposition', lexile: 1150 },
    { word: 'kaleidoscopic', lexile: 1050 }, { word: 'magnanimous', lexile: 1020 }, { word: 'nomenclature', lexile: 1120 },
    { word: 'obsequious', lexile: 1180 }, { word: 'quintessential', lexile: 1080 }, { word: 'recalcitrant', lexile: 1140 },
    { word: 'superfluous', lexile: 1060 }, { word: 'transcendental', lexile: 1110 }, { word: 'ubiquitous', lexile: 1040 },
    { word: 'vicissitudes', lexile: 1250 }, { word: 'wunderkind', lexile: 1070 }, { word: 'xenophobia', lexile: 1060 },
    { word: 'anachronism', lexile: 1130 }, { word: 'cacophony', lexile: 1090 }, { word: 'ebullient', lexile: 1170 },
    { word: 'histrionic', lexile: 1190 }, { word: 'labyrinthine', lexile: 1210 }, { word: 'mendacious', lexile: 1220 },
    { word: 'ostentatious', lexile: 1050 }, { word: 'parsimonious', lexile: 1240 }, { word: 'quixotic', lexile: 1160 },
    { word: 'surreptitious', lexile: 1230 }, { word: 'unconscionable', lexile: 1260 }, { word: 'vociferous', lexile: 1120 },
    { word: 'aberration', lexile: 1150 }, { word: 'perpicacious', lexile: 1280 }, { word: 'magnificence', lexile: 1010 },
    { word: 'extemporaneous', lexile: 1290 }, { word: 'pusillanimous', lexile: 1300 }, { word: 'tergiversation', lexile: 1350 },
    { word: 'sesquipedalian', lexile: 1400 }, { word: 'antidisestablishmentarianism', lexile: 1500 },
    { word: 'palaeontologist', lexile: 1050 }, { word: 'circumlocution', lexile: 1185 }, { word: 'verisimilitude', lexile: 1275 },
    { word: 'conspicuous', lexile: 1025 }, { word: 'epistemology', lexile: 1310 }, { word: 'iconoclastic', lexile: 1145 },
    { word: 'mellifluous', lexile: 1035 }, { word: 'obfuscation', lexile: 1205 }, { word: 'panegyric', lexile: 1225 },
    { word: 'recapitulate', lexile: 1095 }, { word: 'solipsistic', lexile: 1320 }, { word: 'unfathomable', lexile: 1075 },
    { word: 'vituperative', lexile: 1265 }, { word: 'zealotry', lexile: 1045 }, { word: 'philological', lexile: 1155 }
  ]
};
